### ISSUE TITLE
It doesn't work, see the image below

### ISSUE THREAD

**Issue by antonioedinadson** [jingjing0327/WeChatVideoDownloader#1]
![07a2845b-7418-48fa-a1bf-a7e291e1e099](https://github.com/jingjing0327/WeChatVideoDownloader/assets/47501385/ba6579c3-6041-4168-ae39-c7b2f0da5ba9)

**There was no response at all.**

**Comment by jingjing0327** [comment]
try again

**Comment by antonioedinadson** [comment]
> try again

Does not work.
